name: Test

on: [push]

jobs:
  rake-spec:
    name: rake-spec
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Run specs
      run: |
        bundle install
        bundle exec rspec
    - name: Run rake spec
      run: |
        rake spec